
project_id = "zsiwyvbiwyppkftcaeph"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://zsiwyvbiwyppkftcaeph.lovable.app"
additional_redirect_urls = ["https://zsiwyvbiwyppkftcaeph.lovable.app", "https://35a2fb2e-373c-4b2c-9d60-21d62f5f639a.lovableproject.com"]

[functions]
[functions.ai-integration]
verify_jwt = true
