
project_id = "zsiwyvbiwyppkftcaeph"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]

[functions]
[functions.ai-integration]
verify_jwt = true
