
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsiwyvbiwyppkftcaeph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaXd5dmJpd3lwcGtmdGNhZXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDc3OTEsImV4cCI6MjA1ODU4Mzc5MX0.3f32wT_1wmyVCqUhfnJpHCdoouYnuPyUWtR41N0-rys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
